package com.coffee.jiahui.mapper;

import java.util.Map;

import com.coffee.jiahui.domain.StudentMessage;

public interface StudentMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_message
     *
     * @mbg.generated Sun Apr 14 17:21:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_message
     *
     * @mbg.generated Sun Apr 14 17:21:34 CST 2019
     */
    int insert(StudentMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_message
     *
     * @mbg.generated Sun Apr 14 17:21:34 CST 2019
     */
    int insertSelective(StudentMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_message
     *
     * @mbg.generated Sun Apr 14 17:21:34 CST 2019
     */
    StudentMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_message
     *
     * @mbg.generated Sun Apr 14 17:21:34 CST 2019
     */
    int updateByPrimaryKeySelective(StudentMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_message
     *
     * @mbg.generated Sun Apr 14 17:21:34 CST 2019
     */
    int updateByPrimaryKey(StudentMessage record);
    
    void insertStudentMessage(Map<String, Object> map);
}