package com.coffee.jiahui.mapper;

import com.coffee.jiahui.domain.StudentScore;

public interface StudentScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Sun Apr 14 17:21:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Sun Apr 14 17:21:34 CST 2019
     */
    int insert(StudentScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Sun Apr 14 17:21:34 CST 2019
     */
    int insertSelective(StudentScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Sun Apr 14 17:21:34 CST 2019
     */
    StudentScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Sun Apr 14 17:21:34 CST 2019
     */
    int updateByPrimaryKeySelective(StudentScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbg.generated Sun Apr 14 17:21:34 CST 2019
     */
    int updateByPrimaryKey(StudentScore record);
}